version: '3'

services:
  demowebapi:
    image: demowebapi
    build:
      context: ./DemoWebApi
      dockerfile: Dockerfile

  rabbitmq:
    image: rabbitmq:3-management
    ports:
        - "8080:15672"
        - "5672:5672"